### ISSUE TITLE
Fresh run : django.db.utils.ProgrammingError: relation "main_visits" does not exist error

### ISSUE THREAD

**Issue by am1ru1** [mimischi/django-docker#8]
Got the following error fresh from baking. Am I missing something?

```
django.db.utils.ProgrammingError
django.db.utils.ProgrammingError: relation "main_visits" does not exist
LINE 1: ...CT "main_visits"."id", "main_visits"."count" FROM "main_visi...
                                                             ^
```

Trace:
```
web_1  | 10.0.2.2 - - [24/Feb/2018 04:52:44] "GET / HTTP/1.1" 500 -
web_1  | Traceback (most recent call last):
web_1  |   File "/usr/local/lib/python3.6/site-packages/django/contrib/staticfiles/handlers.py", line 66, in __call__
web_1  |     return self.application(environ, start_response)
web_1  |   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/wsgi.py", line 146, in __call__
web_1  |     response = self.get_response(request)
web_1  |   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 81, in get_response
web_1  |     response = self._middleware_chain(request)
web_1  |   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 37, in inner
web_1  |     response = response_for_exception(request, exc)
web_1  |   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 87, in response_for_exception
web_1  |     response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
web_1  |   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 122, in handle_uncaught_exception
web_1  |     return debug.technical_500_response(request, *exc_info)
web_1  |   File "/usr/local/lib/python3.6/site-packages/django_extensions/management/technical_response.py", line 6, in null_technical_500_response
web_1  |     six.reraise(exc_type, exc_value, tb)
web_1  |   File "/usr/local/lib/python3.6/site-packages/six.py", line 693, in reraise
web_1  |     raise value
web_1  |   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
web_1  |     response = get_response(request)
web_1  |   File "/usr/local/lib/python3.6/site-packages/django/utils/deprecation.py", line 95, in __call__
web_1  |     response = self.get_response(request)
web_1  |   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 37, in inner
web_1  |     response = response_for_exception(request, exc)
web_1  |   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 87, in response_for_exception
web_1  |     response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
web_1  |   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 122, in handle_uncaught_exception
web_1  |     return debug.technical_500_response(request, *exc_info)
web_1  |   File "/usr/local/lib/python3.6/site-packages/django_extensions/management/technical_response.py", line 6, in null_technical_500_response
web_1  |     six.reraise(exc_type, exc_value, tb)
web_1  |   File "/usr/local/lib/python3.6/site-packages/six.py", line 693, in reraise
web_1  |     raise value
web_1  |   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
web_1  |     response = get_response(request)
web_1  |   File "/usr/local/lib/python3.6/site-packages/django/utils/deprecation.py", line 95, in __call__
web_1  |     response = self.get_response(request)
web_1  |   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 37, in inner
web_1  |     response = response_for_exception(request, exc)
web_1  |   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 87, in response_for_exception
web_1  |     response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
web_1  |   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 122, in handle_uncaught_exception
web_1  |     return debug.technical_500_response(request, *exc_info)
web_1  |   File "/usr/local/lib/python3.6/site-packages/django_extensions/management/technical_response.py", line 6, in null_technical_500_response
web_1  |     six.reraise(exc_type, exc_value, tb)
web_1  |   File "/usr/local/lib/python3.6/site-packages/six.py", line 693, in reraise
web_1  |     raise value
web_1  |   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
web_1  |     response = get_response(request)
web_1  |   File "/usr/local/lib/python3.6/site-packages/django/utils/deprecation.py", line 95, in __call__
web_1  |     response = self.get_response(request)
web_1  |   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 37, in inner
web_1  |     response = response_for_exception(request, exc)
web_1  |   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 87, in response_for_exception
web_1  |     response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
web_1  |   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 122, in handle_uncaught_exception
web_1  |     return debug.technical_500_response(request, *exc_info)
web_1  |   File "/usr/local/lib/python3.6/site-packages/django_extensions/management/technical_response.py", line 6, in null_technical_500_response
web_1  |     six.reraise(exc_type, exc_value, tb)
web_1  |   File "/usr/local/lib/python3.6/site-packages/six.py", line 693, in reraise
web_1  |     raise value
web_1  |   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
web_1  |     response = get_response(request)
web_1  |   File "/usr/local/lib/python3.6/site-packages/django/utils/deprecation.py", line 95, in __call__
web_1  |     response = self.get_response(request)
web_1  |   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 37, in inner
web_1  |     response = response_for_exception(request, exc)
web_1  |   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 87, in response_for_exception
web_1  |     response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
web_1  |   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 122, in handle_uncaught_exception
web_1  |     return debug.technical_500_response(request, *exc_info)
web_1  |   File "/usr/local/lib/python3.6/site-packages/django_extensions/management/technical_response.py", line 6, in null_technical_500_response
web_1  |     six.reraise(exc_type, exc_value, tb)
web_1  |   File "/usr/local/lib/python3.6/site-packages/six.py", line 693, in reraise
web_1  |     raise value
web_1  |   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
web_1  |     response = get_response(request)
web_1  |   File "/usr/local/lib/python3.6/site-packages/django/utils/deprecation.py", line 95, in __call__
web_1  |     response = self.get_response(request)
web_1  |   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 37, in inner
web_1  |     response = response_for_exception(request, exc)
web_1  |   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 87, in response_for_exception
web_1  |     response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
web_1  |   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 122, in handle_uncaught_exception
web_1  |     return debug.technical_500_response(request, *exc_info)
web_1  |   File "/usr/local/lib/python3.6/site-packages/django_extensions/management/technical_response.py", line 6, in null_technical_500_response
web_1  |     six.reraise(exc_type, exc_value, tb)
web_1  |   File "/usr/local/lib/python3.6/site-packages/six.py", line 693, in reraise
web_1  |     raise value
web_1  |   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
web_1  |     response = get_response(request)
web_1  |   File "/usr/local/lib/python3.6/site-packages/django/utils/deprecation.py", line 95, in __call__
web_1  |     response = self.get_response(request)
web_1  |   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 37, in inner
web_1  |     response = response_for_exception(request, exc)
web_1  |   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 87, in response_for_exception
web_1  |     response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
web_1  |   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 122, in handle_uncaught_exception
web_1  |     return debug.technical_500_response(request, *exc_info)
web_1  |   File "/usr/local/lib/python3.6/site-packages/django_extensions/management/technical_response.py", line 6, in null_technical_500_response
web_1  |     six.reraise(exc_type, exc_value, tb)
web_1  |   File "/usr/local/lib/python3.6/site-packages/six.py", line 693, in reraise
web_1  |     raise value
web_1  |   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
web_1  |     response = get_response(request)
web_1  |   File "/usr/local/lib/python3.6/site-packages/django/utils/deprecation.py", line 95, in __call__
web_1  |     response = self.get_response(request)
web_1  |   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 37, in inner
web_1  |     response = response_for_exception(request, exc)
web_1  |   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 87, in response_for_exception
web_1  |     response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
web_1  |   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 122, in handle_uncaught_exception
web_1  |     return debug.technical_500_response(request, *exc_info)
web_1  |   File "/usr/local/lib/python3.6/site-packages/django_extensions/management/technical_response.py", line 6, in null_technical_500_response
web_1  |     six.reraise(exc_type, exc_value, tb)
web_1  |   File "/usr/local/lib/python3.6/site-packages/six.py", line 693, in reraise
web_1  |     raise value
web_1  |   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
web_1  |     response = get_response(request)
web_1  |   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
web_1  |     response = self.process_exception_by_middleware(e, request)
web_1  |   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
web_1  |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
web_1  |   File "/app/main/views.py", line 11, in home
web_1  |     c = Visits.objects.get(pk=1)
web_1  |   File "/usr/local/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
web_1  |     return getattr(self.get_queryset(), name)(*args, **kwargs)
web_1  |   File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 397, in get
web_1  |     num = len(clone)
web_1  |   File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 254, in __len__
web_1  |     self._fetch_all()
web_1  |   File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 1179, in _fetch_all
web_1  |     self._result_cache = list(self._iterable_class(self))
web_1  |   File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 53, in __iter__
web_1  |     results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
web_1  |   File "/usr/local/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1064, in execute_sql
web_1  |     cursor.execute(sql, params)
web_1  |   File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 100, in execute
web_1  |     return super().execute(sql, params)
web_1  |   File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 68, in execute
web_1  |     return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
web_1  |   File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
web_1  |     return executor(sql, params, many, context)
web_1  |   File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute
web_1  |     return self.cursor.execute(sql, params)
web_1  |   File "/usr/local/lib/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
web_1  |     raise dj_exc_value.with_traceback(traceback) from exc_value
web_1  |   File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute
web_1  |     return self.cursor.execute(sql, params)
web_1  | django.db.utils.ProgrammingError: relation "main_visits" does not exist
web_1  | LINE 1: ...CT "main_visits"."id", "main_visits"."count" FROM "main_visi...
web_1  |              
```

**Comment by am1ru1** [comment]
Seems like running docker-compose does not migrate the db automatically. Have to run 
`docker-compose run --rm web python manage.py migrate`

However even after manually running the migrate command, got the following PG error when docker-compose up:
```
db_1   | LOG:  autovacuum launcher started
db_1   | ERROR:  relation "main_visits" does not exist at character 55
db_1   | STATEMENT:  SELECT "main_visits"."id", "main_visits"."count" FROM "main_visits" WHERE "main_visits"."id" = 1
db_1   | ERROR:  relation "main_visits" does not exist at character 55
db_1   | STATEMENT:  SELECT "main_visits"."id", "main_visits"."count" FROM "main_visits" WHERE "main_visits"."id" = 1
db_1   | LOG:  received smart shutdown request
```

**Comment by am1ru1** [comment]
After executing the home page, the `ERROR:  relation "main_visits" does not exist at character 55` have stopped popping. How do you prevent this error on a fresh bake?

**Comment by chgad** [comment]
Hi @vnoxygen,

indeed the automatic migrate isn't implemented for the local development version, yet it would be a great
idea to do so. I think the best place to set the migrate command is in the `start.sh` which is run by `docker-compose.yml` when starting the container. 
@mimischi Any thoughts about this ?

P.S.:

> However even after manually running the migrate command, got the following PG error when docker-compose up

I can not reproduce this.

**Comment by am1ru1** [comment]
If I understand the proposal's flow, the migrate command will always run after closing the server (not just on any failure. I actually thought to have the migrate commands at Makefile and have the wiki/readme instructions to run the make build.

```
 while true; do
     echo "Re-starting Django runserver_plus!"	     echo "Re-starting Django runserver_plus!"
     python manage.py runserver_plus 0.0.0.0:8000	     python manage.py runserver_plus 0.0.0.0:8000
+    python manage.py migrate --no-input
     sleep 2	     sleep 2
 done	 done
```


```
build:
	docker-compose build
        docker-compose run --rm web python manage.py migrate
```

**Comment by chgad** [comment]
I thought of the fact that the server might close when migrations where not applied.
In generel i like the behavior that the "system" migrates allways. Of course one, could take the `migrate` out of the loop and let it only run once when bring up the container.

>  I actually thought to have the migrate commands at Makefile

That's a great idea too!

**Comment by mimischi** [comment]
I don't think applying migrations automatically is a good thing, therefore we should not put it into `start.sh`. There is certainly cases where you do not want to apply migrations immediately, but maybe want to change things first or check that the planned migration ist actually what you want to do.

Having an extra entry in `Makefile` may not be the worst idea. I'll have a look what the problem with the fresh installs is.

**Comment by mimischi** [comment]
@vnoxygen I just re-created this repository (running `docker-compose down` to remove all containers and `make build` to rebuild).

I can reproduce the error, when you have not migrated anything yet. After migration (` docker-compose run --rm web python manage.py migrate`), I do not get your aforementioned error. Could you try to re-create the system?

This should do it:
```bash
$ docker-compose down
$ make build
$ docker-compose run --rm web python manage.py migrate
$ docker-compose up
```

**Comment by am1ru1** [comment]
Looks good. No issue. Confirmed from fresh install, readme is good too. Let's merge, @mimischi
